In [66]:
import pandas as pd
import datetime as dt
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [67]:
df_01 = pd.read_csv('df_01.csv')
df_02 = pd.read_csv('df_02.csv')
df_03 = pd.read_csv('df_03.csv')
df_04 = pd.read_csv('df_04.csv')
df_05 = pd.read_csv('df_05.csv')
df_06 = pd.read_csv('df_06.csv')
df_07 = pd.read_csv('df_07.csv')
df_08 = pd.read_csv('df_08.csv')
df_09 = pd.read_csv('df_09.csv')


In [68]:
df_01['weekend']=df_01['weekday'].isin(['Saturday','Sunday']).astype(int)
df_02['weekend']=df_02['weekday'].isin(['Saturday','Sunday']).astype(int)
df_03['weekend']=df_03['weekday'].isin(['Saturday','Sunday']).astype(int)
df_04['weekend']=df_04['weekday'].isin(['Saturday','Sunday']).astype(int)
df_05['weekend']=df_05['weekday'].isin(['Saturday','Sunday']).astype(int)
df_06['weekend']=df_06['weekday'].isin(['Saturday','Sunday']).astype(int)
df_07['weekend']=df_07['weekday'].isin(['Saturday','Sunday']).astype(int)
df_08['weekend']=df_08['weekday'].isin(['Saturday','Sunday']).astype(int)
df_09['weekend']=df_09['weekday'].isin(['Saturday','Sunday']).astype(int)

df_01['daytime']=df_01['start_hour'].isin([6,7,8,9,10,11,12,13,14,15,16,17,18,19]).astype(int)
df_02['daytime']=df_02['start_hour'].isin([6,7,8,9,10,11,12,13,14,15,16,17,18,19]).astype(int)
df_03['daytime']=df_03['start_hour'].isin([6,7,8,9,10,11,12,13,14,15,16,17,18,19]).astype(int)
df_04['daytime']=df_04['start_hour'].isin([6,7,8,9,10,11,12,13,14,15,16,17,18,19]).astype(int)
df_05['daytime']=df_05['start_hour'].isin([6,7,8,9,10,11,12,13,14,15,16,17,18,19]).astype(int)
df_06['daytime']=df_06['start_hour'].isin([6,7,8,9,10,11,12,13,14,15,16,17,18,19]).astype(int)
df_07['daytime']=df_07['start_hour'].isin([6,7,8,9,10,11,12,13,14,15,16,17,18,19]).astype(int)
df_08['daytime']=df_08['start_hour'].isin([6,7,8,9,10,11,12,13,14,15,16,17,18,19]).astype(int)
df_09['daytime']=df_09['start_hour'].isin([6,7,8,9,10,11,12,13,14,15,16,17,18,19]).astype(int)


In [69]:
df_01

date         day         time  start_hour   weekday  \
0     2022-03-01 00:00:00  2022-03-01  00:00-01:00           0   Tuesday   
1     2022-03-01 01:00:00  2022-03-01  01:00-02:00           1   Tuesday   
2     2022-03-01 02:00:00  2022-03-01  02:00-03:00           2   Tuesday   
3     2022-03-01 03:00:00  2022-03-01  03:00-04:00           3   Tuesday   
4     2022-03-01 04:00:00  2022-03-01  04:00-05:00           4   Tuesday   
...                   ...         ...          ...         ...       ...   
7339  2022-12-31 19:00:00  2022-12-31  19:00-20:00          19  Saturday   
7340  2022-12-31 20:00:00  2022-12-31  20:00-21:00          20  Saturday   
7341  2022-12-31 21:00:00  2022-12-31  21:00-22:00          21  Saturday   
7342  2022-12-31 22:00:00  2022-12-31  22:00-23:00          22  Saturday   
7343  2022-12-31 23:00:00  2022-12-31  23:00-24:00          23  Saturday   

      LC_HUMIDITY  LC_RAININ  LC_TEMP_QCL3_list  school  loko  depot  \
0       78.809524        0.0           1.732657     1.0   1.0    0.0   
1       77.738095        0.0           1.727462     1.0   1.0    0.0   
2       76.714286        0.0           1.934884     1.0   1.0    0.0   
3       79.023810        0.0           1.647822     1.0   1.0    0.0   
4       79.928571        0.0           1.468759     1.0   1.0    0.0   
...           ...        ...                ...     ...   ...    ...   
7339    57.952381        0.0          15.955844     1.0   0.0    0.0   
7340    56.500000        0.0          16.187194     1.0   0.0    0.0   
7341    56.261905        0.0          16.059805     1.0   0.0    0.0   
7342    54.976190        0.0          16.136172     1.0   0.0    0.0   
7343    52.452381        0.0          16.415485     1.0   0.0    0.0   

       location   Latitude  Longitude  laf50_per_hour   baseline  noisiness  \
0     Number 35  50.877146   4.700688             NaN  49.667618      False   
1     Number 35  50.877146   4.700688             NaN  49.667618      False   
2     Number 35  50.877146   4.700688             NaN  49.667618      False   
3     Number 35  50.877146   4.700688             NaN  49.667618      False   
4     Number 35  50.877146   4.700688             NaN  49.667618      False   
...         ...        ...        ...             ...        ...        ...   
7339  Number 35  50.877146   4.700688             NaN  48.764934      False   
7340  Number 35  50.877146   4.700688             NaN  48.898419      False   
7341  Number 35  50.877146   4.700688             NaN  48.898419      False   
7342  Number 35  50.877146   4.700688             NaN  48.898419      False   
7343  Number 35  50.877146   4.700688             NaN  48.898419      False   

      weekend  daytime  
0           0        0  
1           0        0  
2           0        0  
3           0        0  
4           0        0  
...       ...      ...  
7339        1        1  
7340        1        0  
7341        1        0  
7342        1        0  
7343        1        0  

[7344 rows x 19 columns]

In [70]:
df_01 = df_01.dropna(subset=['laf50_per_hour'])
df_02 = df_02.dropna(subset=['laf50_per_hour'])
df_03 = df_03.dropna(subset=['laf50_per_hour'])
df_04 = df_04.dropna(subset=['laf50_per_hour'])
df_05 = df_05.dropna(subset=['laf50_per_hour'])
df_06 = df_06.dropna(subset=['laf50_per_hour'])
df_07 = df_07.dropna(subset=['laf50_per_hour'])
df_08 = df_08.dropna(subset=['laf50_per_hour'])
df_09 = df_09.dropna(subset=['laf50_per_hour'])

In [71]:
len(df_01), len(df_02), len(df_03), len(df_04), len(df_05), len(df_06), len(df_07), len(df_08), len(df_09)  
# df_04, df_08 has few data

(6428, 6383, 7343, 1831, 7341, 7343, 6087, 0, 6254)

# Selecting Feature and Splitting Data

In [72]:
X_01 = df_01[['LC_HUMIDITY', 'LC_RAININ','LC_TEMP_QCL3_list','school','loko','depot','weekend','daytime']]
X_02 = df_02[['LC_HUMIDITY', 'LC_RAININ','LC_TEMP_QCL3_list','school','loko','depot','weekend','daytime']]
X_03 = df_03[['LC_HUMIDITY', 'LC_RAININ','LC_TEMP_QCL3_list','school','loko','depot','weekend','daytime']]
X_04 = df_04[['LC_HUMIDITY', 'LC_RAININ','LC_TEMP_QCL3_list','school','loko','depot','weekend','daytime']]
X_05 = df_05[['LC_HUMIDITY', 'LC_RAININ','LC_TEMP_QCL3_list','school','loko','depot','weekend','daytime']]
X_06 = df_06[['LC_HUMIDITY', 'LC_RAININ','LC_TEMP_QCL3_list','school','loko','depot','weekend','daytime']]
X_07 = df_07[['LC_HUMIDITY', 'LC_RAININ','LC_TEMP_QCL3_list','school','loko','depot','weekend','daytime']]
# X_08 = df_08[['LC_HUMIDITY', 'LC_RAININ','LC_TEMP_QCL3_list','school','loko','depot','weekend','daytime']]
X_09 = df_09[['LC_HUMIDITY', 'LC_RAININ','LC_TEMP_QCL3_list','school','loko','depot','weekend','daytime']]
y_01 = df_01['noisiness']
y_02 = df_02['noisiness']
y_03 = df_03['noisiness']
y_04 = df_04['noisiness']
y_05 = df_05['noisiness']
y_06 = df_06['noisiness']
y_07 = df_07['noisiness']
# y_08 = df_08['noisiness']
y_09 = df_09['noisiness']


In [73]:
# split X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_01_train, X_01_test, y_01_train, y_01_test = train_test_split(X_01, y_01, test_size=0.3, random_state=16)
X_02_train, X_02_test, y_02_train, y_02_test = train_test_split(X_02, y_02, test_size=0.3, random_state=16)
X_03_train, X_03_test, y_03_train, y_03_test = train_test_split(X_03, y_03, test_size=0.3, random_state=16)
X_04_train, X_04_test, y_04_train, y_04_test = train_test_split(X_04, y_04, test_size=0.3, random_state=16)
X_05_train, X_05_test, y_05_train, y_05_test = train_test_split(X_05, y_05, test_size=0.3, random_state=16)
X_06_train, X_06_test, y_06_train, y_06_test = train_test_split(X_06, y_06, test_size=0.3, random_state=16)
X_07_train, X_07_test, y_07_train, y_07_test = train_test_split(X_07, y_07, test_size=0.3, random_state=16)
# X_08_train, X_08_test, y_08_train, y_08_test = train_test_split(X_08, y_08, test_size=0.3, random_state=16)
X_09_train, X_09_test, y_09_train, y_09_test = train_test_split(X_09, y_09, test_size=0.3, random_state=16)

# logistics regression

Number35

In [74]:
# import the class
from sklearn.linear_model import LogisticRegression

# instantiate the model (using the default parameters)
logreg_01 = LogisticRegression(random_state=16,max_iter=200).fit(X_01_train, y_01_train)
y_01_pred = logreg_01.predict(X_01_test)

# import the metrics class
from sklearn import metrics

cnf_matrix_01 = metrics.confusion_matrix(y_01_test, y_01_pred)
cnf_matrix_01

array([[458, 422],
       [281, 768]])

In [75]:
from sklearn.metrics import classification_report
print(classification_report(y_01_test, y_01_pred))

              precision    recall  f1-score   support

       False       0.62      0.52      0.57       880
        True       0.65      0.73      0.69      1049

    accuracy                           0.64      1929
   macro avg       0.63      0.63      0.63      1929
weighted avg       0.63      0.64      0.63      1929



Corner of the Parkstraat & Naamse straat

In [76]:
# import the class
from sklearn.linear_model import LogisticRegression

# instantiate the model (using the default parameters)
logreg_06 = LogisticRegression(random_state=16,max_iter=200).fit(X_06_train, y_06_train)
y_06_pred = logreg_06.predict(X_06_test)

# import the metrics class
from sklearn import metrics

cnf_matrix_06 = metrics.confusion_matrix(y_06_test, y_06_pred)
cnf_matrix_06

array([[458, 579],
       [326, 840]])

In [77]:
from sklearn.metrics import classification_report
print(classification_report(y_06_test, y_06_pred))

              precision    recall  f1-score   support

       False       0.58      0.44      0.50      1037
        True       0.59      0.72      0.65      1166

    accuracy                           0.59      2203
   macro avg       0.59      0.58      0.58      2203
weighted avg       0.59      0.59      0.58      2203



# XGBoost

Number35

In [78]:
import xgboost as xgb
xgb_model_01 = xgb.XGBClassifier(objective="binary:logistic", random_state=42).fit(X_01, y_01)
y_01_pred = xgb_model_01.predict(X_01_test)

# import the metrics class
from sklearn import metrics

cnf_matrix_01 = metrics.confusion_matrix(y_01_test, y_01_pred)
cnf_matrix_01

array([[710, 170],
       [120, 929]])

In [79]:
from sklearn.metrics import classification_report
print(classification_report(y_01_test, y_01_pred))

              precision    recall  f1-score   support

       False       0.86      0.81      0.83       880
        True       0.85      0.89      0.86      1049

    accuracy                           0.85      1929
   macro avg       0.85      0.85      0.85      1929
weighted avg       0.85      0.85      0.85      1929



Corner of the Parkstraat & Naamse straat

In [80]:
import xgboost as xgb
xgb_model_06 = xgb.XGBClassifier(objective="binary:logistic", random_state=42).fit(X_06, y_06)
y_06_pred = xgb_model_01.predict(X_06_test)

# import the metrics class
from sklearn import metrics

cnf_matrix_06 = metrics.confusion_matrix(y_06_test, y_06_pred)
cnf_matrix_06

array([[644, 393],
       [294, 872]])

In [81]:
from sklearn.metrics import classification_report
print(classification_report(y_06_test, y_06_pred))

              precision    recall  f1-score   support

       False       0.69      0.62      0.65      1037
        True       0.69      0.75      0.72      1166

    accuracy                           0.69      2203
   macro avg       0.69      0.68      0.68      2203
weighted avg       0.69      0.69      0.69      2203



# Decision Tree

In [87]:
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
# Create Decision Tree classifer object
clf_01 = DecisionTreeClassifier(random_state=42).fit(X_01_train,y_01_train)
y_01_pred = clf_01.predict(X_01_test)

# import the metrics class
from sklearn import metrics

cnf_matrix_01 = metrics.confusion_matrix(y_01_test, y_01_pred)
cnf_matrix_01

array([[536, 344],
       [353, 696]])

In [88]:
from sklearn.metrics import classification_report
print(classification_report(y_01_test, y_01_pred))

              precision    recall  f1-score   support

       False       0.60      0.61      0.61       880
        True       0.67      0.66      0.67      1049

    accuracy                           0.64      1929
   macro avg       0.64      0.64      0.64      1929
weighted avg       0.64      0.64      0.64      1929



In [89]:
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
# Create Decision Tree classifer object
clf_06 = DecisionTreeClassifier(random_state=42).fit(X_06_train,y_06_train)
y_06_pred = clf_06.predict(X_06_test)

# import the metrics class
from sklearn import metrics

cnf_matrix_06 = metrics.confusion_matrix(y_06_test, y_06_pred)
cnf_matrix_06

array([[596, 441],
       [404, 762]])

In [86]:
from sklearn.metrics import classification_report
print(classification_report(y_06_test, y_06_pred))

              precision    recall  f1-score   support

       False       0.60      0.58      0.59      1037
        True       0.64      0.66      0.65      1166

    accuracy                           0.62      2203
   macro avg       0.62      0.62      0.62      2203
weighted avg       0.62      0.62      0.62      2203

